import { AlertTriangle,LoaderCircle,Search,X } from 'lucide-react';
import type { ReactNode } from 'react';
export function Button({children,variant='primary',className='',...p}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'danger'}){return <button className={`${variant==='primary'?'btn-primary':variant==='danger'?'btn bg-red-600 text-white hover:bg-red-700':'btn-secondary'} ${className}`} {...p}>{children}</button>}
export function Badge({children,tone='green'}:{children:ReactNode;tone?:'green'|'amber'|'red'|'gray'|'purple'}){const c={green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',red:'bg-red-50 text-red-700',gray:'bg-stone-100 text-stone-600',purple:'bg-violet-50 text-violet-700'}[tone];return <span className={`badge ${c}`}>{children}</span>}
export function Modal({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/50 p-4 backdrop-blur-sm" onMouseDown={onClose}><div className="card max-h-[90vh] w-full max-w-lg overflow-auto p-6" onMouseDown={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-extrabold">{title}</h2><button onClick={onClose} className="rounded-lg p-2 hover:bg-stone-100"><X size={20}/></button></div>{children}</div></div>}
export function Confirm({open,title,body,onClose,onConfirm}:{open:boolean;title:string;body:string;onClose:()=>void;onConfirm:()=>void}){return <Modal open={open} title={title} onClose={onClose}><div className="mb-5 flex gap-3 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="shrink-0"/>{body}</div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Keep it</Button><Button variant="danger" onClick={onConfirm}>Confirm</Button></div></Modal>}
export function Loading({cards=4}:{cards?:number}){return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:cards},(_,i)=><div key={i} className="skeleton h-72"/>)}</div>}
export function Empty({title='Nothing here yet',body='Try changing your filters or check back later.'}:{title?:string;body?:string}){return <div className="card py-16 text-center"><div className="mx-auto mb-3 grid h-12 w-12 place-items-center rounded-2xl bg-stone-100"><Search/></div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm text-stone-500">{body}</p></div>}
export function Spinner(){return <LoaderCircle className="animate-spin"/>}
