import {OrderModel} from '../models/Order.js';
export function productView(product:any,privateFields=false){const boosted=Boolean(product.boosted&&(!product.boostEnds||product.boostEnds.getTime()>Date.now()));const variants=product.variants.length?product.variants:[{_id:undefined,size:'',color:'',sku:'',price:product.price,discountPrice:product.discountPrice,costPrice:product.costPrice??0,packagingCost:product.packagingCost??0,otherCost:product.otherCost??0,quantity:product.quantity}];const cheapest=variants.reduce((best:any,item:any)=>(item.discountPrice??item.price)<(best.discountPrice??best.price)?item:best);const regularPrice=cheapest.price;const discountPrice=cheapest.discountPrice!=null&&cheapest.discountPrice<regularPrice?cheapest.discountPrice:undefined;const sellerId=product.sellerId?._id??product.sellerId;return {id:String(product._id),sellerId:String(sellerId),seller:product.seller,sellerAcceptingOrders:product.sellerId?.acceptingOrders??true,name:product.name,description:product.description,category:product.category==='Food'?product.subcategory:product.category,subcategory:product.subcategory,price:regularPrice,discountPrice,image:product.images[0],images:product.images,variants:variants.map((item:any)=>({id:item._id?String(item._id):undefined,size:item.size,color:item.color,sku:item.sku,price:item.price,discountPrice:item.discountPrice,...(privateFields?{costPrice:item.costPrice??0,packagingCost:item.packagingCost??0,otherCost:item.otherCost??0}:{}),quantity:item.quantity})),quantity:variants.reduce((sum:number,item:any)=>sum+item.quantity,0),status:product.status,boosted,boostEnds:boosted?product.boostEnds?.toISOString().slice(0,10):undefined,prepMinutes:product.prepMinutes,dietary:product.dietary,spicy:product.spicy,ingredients:product.ingredients,deliverySlots:product.deliverySlots,rating:product.rating,orders:product.orders??0,seo:{title:product.seoTitle??'',keywords:product.searchKeywords??[],metaDescription:product.metaDescription??'',score:seoScore(product),updatedAt:product.updatedAt?.toISOString().slice(0,10)??''}}}

function seoScore(product:any){const title=String(product.seoTitle??'').trim(),description=String(product.metaDescription??'').trim(),keywords=(product.searchKeywords??[]) as string[];const checks=[title.length>=30&&title.length<=60,description.length>=80&&description.length<=160,keywords.length>=3,keywords.some(keyword=>title.toLowerCase().includes(keyword.toLowerCase())),product.description.length>=120,product.images.length>=3,Boolean(product.category&&product.subcategory)];return Math.round(checks.filter(Boolean).length/checks.length*100)}

export async function productViews(products:any[],privateFields=false){
 if(!products.length)return [];
 const rows=await OrderModel.aggregate([{$match:{productId:{$in:products.map(product=>product._id)},status:{$in:['COMPLETED','DELIVERED']}}},{$group:{_id:'$productId',units:{$sum:'$quantity'}}}]);
 const units=new Map(rows.map(row=>[String(row._id),row.units]));
 return products.map(product=>productView({...((typeof product.toObject==='function')?product.toObject():product),orders:units.get(String(product._id))??0},privateFields));
}
