import {Router} from 'express';
import {z} from 'zod';
import {requireAuth,requireRole} from '../middleware/auth.js';
import {ProductModel} from '../models/Product.js';
import {publicUser,UserModel} from '../models/User.js';
import {ReactivationRequestModel} from '../models/ReactivationRequest.js';
import {invalidateAuthCache} from '../middleware/auth.js';

export const adminUserRouter=Router();
adminUserRouter.use(requireAuth,requireRole('ADMIN'));
adminUserRouter.get('/',async(_req,res,next)=>{try{const users=await UserModel.find().sort({createdAt:-1});res.json({success:true,message:'Users loaded',data:users.map(user=>publicUser(user as never))})}catch(error){next(error)}});
adminUserRouter.patch('/:id/status',async(req,res,next)=>{try{const input=z.object({status:z.enum(['ACTIVE','SUSPENDED','BANNED']),reason:z.string().trim().max(1000).optional(),durationDays:z.number().int().positive().max(3650).nullable().optional()}).parse(req.body);if(req.params.id===req.authUser!.id){res.status(400).json({success:false,message:'You cannot moderate your own account'});return}const target=await UserModel.findById(req.params.id).select('+tokenVersion');if(!target){res.status(404).json({success:false,message:'User not found'});return}if(target.role==='ADMIN'){res.status(403).json({success:false,message:'Admin accounts cannot be moderated here'});return}if(input.status!=='ACTIVE'&&!input.reason){res.status(400).json({success:false,message:'A moderation reason is required'});return}target.status=input.status;target.restrictionReason=input.status==='ACTIVE'?undefined:input.reason;target.restrictionEnds=input.status==='ACTIVE'||input.durationDays==null?undefined:new Date(Date.now()+input.durationDays*86400000);if(input.status!=='ACTIVE')target.tokenVersion+=1;await target.save();invalidateAuthCache(String(target._id));if(input.status==='ACTIVE')await ReactivationRequestModel.updateMany({userId:target._id,status:'PENDING'},{status:'APPROVED'});res.json({success:true,message:`User ${input.status.toLowerCase()}`,data:publicUser(target as never)})}catch(error){next(error)}});
adminUserRouter.get('/:id/analytics',async(req,res,next)=>{try{const seller=await UserModel.findOne({_id:req.params.id,role:'SELLER'});if(!seller){res.status(404).json({success:false,message:'Seller not found'});return}const listings=await ProductModel.find({sellerId:seller._id}).sort({orders:-1});const totalSales=listings.reduce((sum,item)=>sum+item.orders,0);const revenue=listings.reduce((sum,item)=>sum+item.orders*(item.discountPrice??item.price),0);res.json({success:true,message:'Seller analytics loaded',data:{seller:publicUser(seller as never),listings:listings.map(item=>({id:String(item._id),name:item.name,image:item.images[0],category:item.category,price:item.price,discountPrice:item.discountPrice,orders:item.orders,rating:item.rating,status:item.status})),sellerOrders:[],totalSales,revenue,activeListings:listings.filter(item=>item.status==='ACTIVE').length,bestSeller:listings[0]??null,averageOrderValue:totalSales?Math.round(revenue/totalSales):0}})}catch(error){next(error)}});
