import {Router} from 'express';
import {z} from 'zod';
import {AnalyticsEventModel} from '../models/AnalyticsEvent.js';
import {ProductModel} from '../models/Product.js';

export const analyticsEventRouter=Router();
const eventBucket=()=>String(Math.floor(Date.now()/600000));
const visitor=(req:any)=>String(req.header('X-Visitor-Id')??'').trim().slice(0,100);
analyticsEventRouter.post('/browse',async(req,res,next)=>{try{const input=z.object({productIds:z.array(z.string().regex(/^[a-f\d]{24}$/i)).min(1).max(40),type:z.enum(['LISTING_IMPRESSION','PRODUCT_VIEW']),query:z.string().trim().max(120).optional(),source:z.enum(['ORGANIC_SEARCH','MARKETPLACE','HOMEPAGE','CATEGORY','RECOMMENDATION','SELLER_STORE','PPC','BOOST','DIRECT','OTHER']).default('MARKETPLACE')}).parse(req.body),visitorId=visitor(req);if(visitorId.length<8){res.status(400).json({success:false,message:'A valid visitor identifier is required'});return}const ids=[...new Set(input.productIds)],products=await ProductModel.find({_id:{$in:ids}}).select('sellerId').lean().maxTimeMS(2000),bucket=eventBucket(),query=input.query?.toLowerCase();const operations=products.flatMap(product=>{const base=[{updateOne:{filter:{visitorId,productId:product._id,type:input.type,eventBucket:bucket},update:{$setOnInsert:{sellerId:product.sellerId,source:input.source}},upsert:true}}];if(input.type==='LISTING_IMPRESSION'&&query)base.push({updateOne:{filter:{visitorId,productId:product._id,type:'SEARCH',eventBucket:bucket},update:{$setOnInsert:{sellerId:product.sellerId,source:'ORGANIC_SEARCH',query}},upsert:true}} as any);return base});if(operations.length)await AnalyticsEventModel.bulkWrite(operations,{ordered:false});res.status(201).json({success:true,message:'Browse events recorded',data:null})}catch(error){next(error)}});
analyticsEventRouter.post('/cart',async(req,res,next)=>{try{const input=z.object({productId:z.string().regex(/^[a-f\d]{24}$/i),quantity:z.coerce.number().int().min(1).max(10000)}).parse(req.body),visitorId=visitor(req);if(visitorId.length<8){res.status(400).json({success:false,message:'A valid visitor identifier is required'});return}const product=await ProductModel.findById(input.productId).select('sellerId');if(!product){res.status(404).json({success:false,message:'Product not found'});return}const previous=await AnalyticsEventModel.findOne({visitorId,productId:product._id,type:'PRODUCT_VIEW'}).sort({createdAt:-1}).select('source campaignId').lean();await AnalyticsEventModel.updateOne({visitorId,productId:product._id,type:'ADD_TO_CART',eventBucket:eventBucket()},{$setOnInsert:{sellerId:product.sellerId,source:previous?.source??'DIRECT',campaignId:previous?.campaignId},$max:{quantity:input.quantity}},{upsert:true});res.status(201).json({success:true,message:'Cart event recorded',data:null})}catch(error){next(error)}});
analyticsEventRouter.post('/funnel',async(req,res,next)=>{try{const input=z.object({productIds:z.array(z.string().regex(/^[a-f\d]{24}$/i)).min(1).max(50),type:z.enum(['CHECKOUT_STARTED','REMOVE_FROM_CART'])}).parse(req.body),visitorId=visitor(req);if(visitorId.length<8){res.status(400).json({success:false,message:'A valid visitor identifier is required'});return}const products=await ProductModel.find({_id:{$in:input.productIds}}).select('sellerId').lean(),bucket=eventBucket();await AnalyticsEventModel.bulkWrite(products.map(product=>({updateOne:{filter:{visitorId,productId:product._id,type:input.type,eventBucket:bucket},update:{$setOnInsert:{sellerId:product.sellerId}},upsert:true}})),{ordered:false});res.status(201).json({success:true,message:'Funnel event recorded',data:null})}catch(error){next(error)}});
