import {Router} from 'express';
import {z} from 'zod';
import {requireAuth,requireRole} from '../middleware/auth.js';
import {CouponModel} from '../models/Coupon.js';
import {OrderModel} from '../models/Order.js';
import {ProductModel} from '../models/Product.js';
import {AnalyticsEventModel} from '../models/AnalyticsEvent.js';
import {PpcCampaignModel} from '../models/PpcCampaign.js';
import {ReviewModel} from '../models/Review.js';
import {CompanyPaymentModel} from '../models/CompanyPayment.js';
import {requestBulkhead} from '../middleware/requestBulkhead.js';

export const sellerAnalyticsRouter=Router();
sellerAnalyticsRouter.use(requireAuth);
sellerAnalyticsRouter.use(requestBulkhead(4,12,4000));
const scopedSellerId=(req:any)=>req.authUser.role==='ADMIN'?z.string().regex(/^[a-f\d]{24}$/i).parse(req.query.sellerId):req.authUser.id;
const finished=(status:string)=>['COMPLETED','DELIVERED'].includes(status);
const round=(value:number)=>Math.round(value*100)/100;
const orderRevenue=(order:{total:number;unitCost?:number|null;quantity:number})=>round(order.total-(order.unitCost??0)*order.quantity);
const delta=(current:number,previous:number)=>previous?round((current-previous)/previous*100):current?100:0;
const DHAKA_OFFSET_MS=6*60*60*1000;
const dhakaDay=(date:Date)=>new Date(date.getTime()+DHAKA_OFFSET_MS).toISOString().slice(0,10);
const dhakaRangeStart=(days:number)=>{const now=new Date(Date.now()+DHAKA_OFFSET_MS);return new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())-DHAKA_OFFSET_MS-(days-1)*86400000)};
const ignoredKeywords=new Set(['a','an','the','and','or','for','with','near','buy','shop','product','products','item','items','best','new']);
const normalizeKeyword=(value:string)=>value.toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,' ').replace(/-/g,' ').split(/\s+/).filter(word=>word.length>=3&&!ignoredKeywords.has(word)).join(' ').trim();
const keywordPhrase=z.string().trim().min(3).max(80).refine(value=>normalizeKeyword(value).length>=3,'Use a meaningful full word or phrase, not filler words');

sellerAnalyticsRouter.get('/product-intelligence-settings',requireRole('SELLER'),async(req,res,next)=>{try{const products=await ProductModel.find({sellerId:req.authUser!.id}).sort({name:1});res.json({success:true,message:'Product intelligence settings loaded',data:products.map(product=>({id:String(product._id),name:product.name,costPrice:product.costPrice??0,packagingCost:product.packagingCost??0,otherCost:product.otherCost??0,seoTitle:product.seoTitle??'',searchKeywords:product.searchKeywords??[],metaDescription:product.metaDescription??''}))})}catch(error){next(error)}});
sellerAnalyticsRouter.patch('/product-intelligence-settings/:id',requireRole('SELLER'),async(req,res,next)=>{try{const input=z.object({costPrice:z.coerce.number().min(0).optional(),packagingCost:z.coerce.number().min(0).optional(),otherCost:z.coerce.number().min(0).optional(),seoTitle:z.string().trim().max(160),searchKeywords:z.array(keywordPhrase).max(30),metaDescription:z.string().trim().max(300)}).parse(req.body);const normalizedKeywords=[...new Set(input.searchKeywords.map(normalizeKeyword).filter(Boolean))];const product=await ProductModel.findOneAndUpdate({_id:req.params.id,sellerId:req.authUser!.id},{...input,searchKeywords:normalizedKeywords},{new:true,runValidators:true});if(!product){res.status(404).json({success:false,message:'Product not found'});return}res.json({success:true,message:'Search metadata updated',data:{id:String(product._id),name:product.name,costPrice:product.costPrice??0,packagingCost:product.packagingCost??0,otherCost:product.otherCost??0,seoTitle:product.seoTitle??'',searchKeywords:product.searchKeywords??[],metaDescription:product.metaDescription??''}})}catch(error){next(error)}});

sellerAnalyticsRouter.get('/premium',requireRole('SELLER','ADMIN'),async(req,res,next)=>{try{
  const sellerId=scopedSellerId(req);if(req.authUser!.role!=='ADMIN'&&!await CompanyPaymentModel.exists({userId:sellerId,product:'PREMIUM_ANALYTICS',status:'SUCCEEDED',paidAt:{$gte:new Date(Date.now()-30*86400000)}})){res.status(403).json({success:false,message:'An active verified premium analytics subscription is required'});return}const days=z.coerce.number().int().min(1).max(365).catch(30).parse(req.query.days);const start=dhakaRangeStart(days);const [events,orders,products,marketProducts,campaigns,reviews]=await Promise.all([AnalyticsEventModel.find({sellerId,createdAt:{$gte:start}}).limit(20001).lean(),OrderModel.find({sellerId,createdAt:{$gte:start}}).limit(20001).lean(),ProductModel.find({sellerId}).limit(2001).lean(),ProductModel.find({sellerId:{$ne:sellerId},status:{$in:['ACTIVE','PRE_ORDER_AVAILABLE']}}).select('category subcategory price discountPrice variants.size variants.color variants.price variants.discountPrice').sort({_id:1}).limit(1000).lean(),PpcCampaignModel.find({sellerId}).limit(2001).lean(),ReviewModel.find({sellerId,createdAt:{$gte:start}}).limit(20001).lean()]);if(events.length>20000||orders.length>20000||products.length>2000||campaigns.length>2000||reviews.length>20000){res.status(422).json({success:false,message:'This analytics selection is too large. Choose a shorter period or use the sales summary.'});return}const completed=orders.filter(order=>finished(order.status));
  const productMetrics=products.map(product=>{const id=String(product._id);const impressions=events.filter(event=>String(event.productId)===id&&event.type==='LISTING_IMPRESSION').length;const views=events.filter(event=>String(event.productId)===id&&event.type==='PRODUCT_VIEW').length;const carts=events.filter(event=>String(event.productId)===id&&event.type==='ADD_TO_CART').length;const productOrders=completed.filter(order=>String(order.productId)===id);const sales=round(productOrders.reduce((sum,order)=>sum+orderRevenue(order),0));return {id,name:product.name,image:product.images[0]??'',status:product.status,rating:product.rating,boosted:product.boosted,impressions,views,carts,orders:productOrders.length,units:productOrders.reduce((sum,order)=>sum+order.quantity,0),sales,ctr:impressions?round(views/impressions*100):0,cartRate:views?round(carts/views*100):0,conversionRate:views?round(productOrders.length/views*100):0,cartToOrderRate:carts?round(productOrders.length/carts*100):0}}).sort((a,b)=>b.sales-a.sales);
  const losses=productMetrics.map(product=>{const issues:string[]=[];const actions:string[]=[];if(product.impressions>=10&&product.ctr<5){issues.push('Low listing click-through rate');actions.push('Improve the main image, title and displayed price')}if(product.views>=5&&product.cartRate<10){issues.push('Views are not becoming cart adds');actions.push('Clarify benefits, variants, images and product description')}if(product.carts>=3&&product.cartToOrderRate<25){issues.push('Cart abandonment is high');actions.push('Review delivery promise, price and checkout offer')}if(product.rating>0&&product.rating<4){issues.push('Rating is reducing buyer confidence');actions.push('Resolve quality issues highlighted in reviews')}if(['PAUSED','OUT_OF_STOCK'].includes(product.status)){issues.push('Listing is not visible in marketplace');actions.push('Activate the listing when ready to sell')}return issues.length?{productId:product.id,product:product.name,severity:issues.length>=2?'HIGH':'MEDIUM',issues,actions,views:product.views,carts:product.carts,orders:product.orders,conversionRate:product.conversionRate}:null}).filter(Boolean);
  const keywordMap=new Map<string,{sessions:Set<string>;views:number;carts:number;orders:number;products:Set<string>}>();for(const event of events.filter(event=>event.type==='SEARCH'&&event.query)){const keyword=normalizeKeyword(event.query!);if(!keyword)continue;const item=keywordMap.get(keyword)??{sessions:new Set<string>(),views:0,carts:0,orders:0,products:new Set<string>()};const timeBucket=Math.floor(new Date(event.createdAt).getTime()/10000);item.sessions.add(`${event.visitorId??'anonymous'}:${timeBucket}`);if(event.productId)item.products.add(String(event.productId));keywordMap.set(keyword,item)}for(const [keyword,item] of keywordMap){const ids=item.products;item.views=events.filter(event=>event.type==='PRODUCT_VIEW'&&event.productId&&ids.has(String(event.productId))).length;item.carts=events.filter(event=>event.type==='ADD_TO_CART'&&event.productId&&ids.has(String(event.productId))).length;item.orders=completed.filter(order=>ids.has(String(order.productId))).length;keywordMap.set(keyword,item)}const keywordCorpus=products.map(product=>normalizeKeyword([product.name,product.category,product.subcategory,...(product.searchKeywords??[])].join(' ')).split(' '));const rawKeywords=[...keywordMap.keys()];const meaningfulKeywords=new Set(rawKeywords.filter(keyword=>keyword.split(' ').some(word=>keywordCorpus.some(words=>words.includes(word)))&&!rawKeywords.some(other=>other!==keyword&&other.startsWith(keyword)&&other.length>keyword.length)));const keywords=[...keywordMap].filter(([keyword])=>meaningfulKeywords.has(keyword)).map(([keyword,item])=>({keyword,searches:item.sessions.size,matchedProducts:item.products.size,views:item.views,carts:item.carts,orders:item.orders,conversionRate:item.views?round(item.orders/item.views*100):0,suggestion:item.orders===0?'Use this keyword naturally in a relevant title and description':item.views>item.orders*10?'Improve the matching listing offer for this keyword':'Strong keyword—keep it prominent'})).sort((a,b)=>b.searches-a.searches);
  const demandMap=new Map<string,{product:string;day:string;period:string;orders:number;units:number;sales:number}>();for(const order of completed){const dhaka=new Date(order.createdAt.toLocaleString('en-US',{timeZone:'Asia/Dhaka'}));const hour=dhaka.getHours();const period=hour<6?'Late night':hour<12?'Morning':hour<17?'Afternoon':hour<21?'Evening':'Night';const day=dhaka.toLocaleDateString('en-US',{weekday:'short'});const key=`${order.productId}:${day}:${period}`;const item=demandMap.get(key)??{product:order.food,day,period,orders:0,units:0,sales:0};item.orders+=1;item.units+=order.quantity;item.sales=round(item.sales+orderRevenue(order));demandMap.set(key,item)}
  const buyerMap=new Map<string,{buyer:string;orders:number;units:number;spend:number}>();for(const order of completed){const key=String(order.buyerId);const buyer=buyerMap.get(key)??{buyer:order.buyer,orders:0,units:0,spend:0};buyer.orders+=1;buyer.units+=order.quantity;buyer.spend=round(buyer.spend+order.total);buyerMap.set(key,buyer)}const customers=[...buyerMap.values()].sort((a,b)=>b.spend-a.spend);const repeatCustomers=customers.filter(customer=>customer.orders>1);
  const ppc=productMetrics.filter(product=>product.boosted).map(product=>{const estimatedSpend=round(product.views*2);return {productId:product.id,product:product.name,impressions:product.impressions,clicks:product.views,ctr:product.ctr,orders:product.orders,sales:product.sales,estimatedSpend,estimatedCpc:2,roas:estimatedSpend?round(product.sales/estimatedSpend):0}});
  const impressions=productMetrics.reduce((sum,item)=>sum+item.impressions,0),views=productMetrics.reduce((sum,item)=>sum+item.views,0),cartAdds=productMetrics.reduce((sum,item)=>sum+item.carts,0),checkoutStarts=events.filter(event=>event.type==='CHECKOUT_STARTED').length,sales=round(completed.reduce((sum,order)=>sum+orderRevenue(order),0)),cost=round(completed.reduce((sum,order)=>sum+(order.unitCost??0)*order.quantity,0)),profit=sales,cancelled=orders.filter(order=>order.status==='CANCELLED');
  const advancedProducts=productMetrics.map(metric=>{const product=products.find(item=>String(item._id)===metric.id)!;const stock=product.variants.length?product.variants.reduce((sum,item)=>sum+item.quantity,0):product.quantity;const preOrder=product.status==='PRE_ORDER_AVAILABLE';const outOfStock=product.status==='OUT_OF_STOCK';const dailyVelocity=metric.units/days;const daysOfCover=!preOrder&&dailyVelocity?round(stock/dailyVelocity):null;const competitor=marketProducts.filter(item=>item.category===product.category&&item.subcategory===product.subcategory);const competitorAverage=competitor.length?round(competitor.reduce((sum,item)=>sum+(item.discountPrice??item.price),0)/competitor.length):null;const contentChecks=[product.name.length>=30,product.description.length>=120,product.images.length>=3,(product.searchKeywords?.length??0)>=3,product.rating>=4,['ACTIVE','PRE_ORDER_AVAILABLE'].includes(product.status),preOrder||stock>0];const listingScore=Math.round(contentChecks.filter(Boolean).length/contentChecks.length*100);const productOrders=completed.filter(order=>String(order.productId)===metric.id);const productProfit=round(productOrders.reduce((sum,order)=>sum+orderRevenue(order),0)),productCost=round(productOrders.reduce((sum,order)=>sum+(order.unitCost??0)*order.quantity,0));const forecast7=round(dailyVelocity*7),forecast30=round(dailyVelocity*30);return {...metric,cost:productCost,profit:productProfit,margin:metric.sales+productCost?round(productProfit/(metric.sales+productCost)*100):0,stock,availabilityMode:preOrder?'PRE_ORDER':outOfStock?'OUT_OF_STOCK':'STOCKED',daysOfCover,reorderQuantity:preOrder?0:Math.max(0,Math.ceil(forecast30-stock)),forecast7,forecast30,listingScore,competitorAverage,priceGap:competitorAverage==null?null:round((product.discountPrice??product.price)-competitorAverage),deadStock:!preOrder&&metric.orders===0&&metric.views<3,qualityActions:[...(product.images.length<3?['Add at least 3 product images']:[]),...(product.description.length<120?['Expand the description with benefits and specifications']:[]),...((product.searchKeywords?.length??0)<3?['Add at least 3 relevant search keywords']:[]),...(product.rating<4?['Improve rating and resolve review complaints']:[])]}});
  const campaignPerformance=campaigns.map(campaign=>{
    const product=advancedProducts.find(item=>item.id===String(campaign.productId));
    const campaignEvents=events.filter(event=>event.source==='PPC'&&String(event.campaignId)===String(campaign._id));
    const campaignOrders=completed.filter(order=>order.attributionSource==='PPC'&&String(order.attributionCampaignId)===String(campaign._id));
    const impressions=campaignEvents.filter(event=>event.type==='LISTING_IMPRESSION').length,clicks=campaignEvents.filter(event=>event.type==='PRODUCT_VIEW').length;
    const spend=round(Math.min(campaign.dailyBudget*days,clicks*campaign.bid)),sales=round(campaignOrders.reduce((sum,order)=>sum+orderRevenue(order),0));
    return {id:String(campaign._id),productId:String(campaign.productId),name:campaign.name,product:product?.name??campaign.name,status:campaign.status,keywords:campaign.keywords,negativeKeywords:campaign.negativeKeywords,dailyBudget:campaign.dailyBudget,bid:campaign.bid,impressions,clicks,ctr:impressions?round(clicks/impressions*100):0,orders:campaignOrders.length,spend,estimatedSpend:spend,sales,acos:sales?round(spend/sales*100):0,roas:spend?round(sales/spend):0};
  });
  const totalPpcSpend=round(campaignPerformance.reduce((sum,item)=>sum+item.spend,0));const alerts=[...advancedProducts.filter(item=>item.daysOfCover!=null&&item.daysOfCover<=7).map(item=>({level:'HIGH',title:`${item.name} may run out in ${item.daysOfCover} days`,action:`Restock ${item.reorderQuantity||Math.ceil(item.forecast30)} units`})),...advancedProducts.filter(item=>item.conversionRate<5&&item.views>=5).map(item=>({level:'MEDIUM',title:`${item.name} has low conversion`,action:'Review price, delivery promise, images and reviews'})),...advancedProducts.filter(item=>item.deadStock).map(item=>({level:'MEDIUM',title:`${item.name} is dead stock`,action:'Improve keywords, bundle it, discount it or pause the listing'}))];
  const reviewSignals=products.map(product=>{const rows=reviews.filter(review=>String(review.productId)===String(product._id));return {product:product.name,reviews:rows.length,average:rows.length?round(rows.reduce((sum,row)=>sum+row.rating,0)/rows.length):0,negative:rows.filter(row=>row.rating<=2).length,commonConcern:rows.filter(row=>row.rating<=2).map(row=>row.comment).slice(0,3)}}).filter(item=>item.reviews);
  const cohortMap=new Map<string,{cohort:string;customers:Set<string>;orders:number;revenue:number}>();for(const order of completed){const cohort=dhakaDay(order.createdAt).slice(0,7);const row=cohortMap.get(cohort)??{cohort,customers:new Set<string>(),orders:0,revenue:0};row.customers.add(String(order.buyerId));row.orders++;row.revenue+=orderRevenue(order);cohortMap.set(cohort,row)}
  const sources=['ORGANIC_SEARCH','MARKETPLACE','HOMEPAGE','CATEGORY','RECOMMENDATION','SELLER_STORE','PPC','BOOST','DIRECT','OTHER'] as const;const traffic=sources.map(source=>{const sourceEvents=events.filter(event=>(event.source??'DIRECT')===source);const sourceOrders=completed.filter(order=>(order.attributionSource??'DIRECT')===source);const sourceImpressions=sourceEvents.filter(event=>event.type==='LISTING_IMPRESSION').length;const clicks=sourceEvents.filter(event=>event.type==='PRODUCT_VIEW').length;const revenue=round(sourceOrders.reduce((sum,order)=>sum+orderRevenue(order),0));return {source,impressions:sourceImpressions,clicks,ctr:sourceImpressions?round(clicks/sourceImpressions*100):0,orders:sourceOrders.length,conversion:clicks?round(sourceOrders.length/clicks*100):0,revenue}}).filter(row=>row.impressions||row.clicks||row.orders);
  const attributed={organic:{orders:completed.filter(order=>['ORGANIC_SEARCH','MARKETPLACE','HOMEPAGE','CATEGORY','RECOMMENDATION','SELLER_STORE','DIRECT'].includes(order.attributionSource??'DIRECT')).length,revenue:round(completed.filter(order=>['ORGANIC_SEARCH','MARKETPLACE','HOMEPAGE','CATEGORY','RECOMMENDATION','SELLER_STORE','DIRECT'].includes(order.attributionSource??'DIRECT')).reduce((sum,order)=>sum+orderRevenue(order),0))},ppc:{orders:completed.filter(order=>order.attributionSource==='PPC').length,revenue:round(completed.filter(order=>order.attributionSource==='PPC').reduce((sum,order)=>sum+orderRevenue(order),0))},boost:{orders:completed.filter(order=>order.attributionSource==='BOOST').length,revenue:round(completed.filter(order=>order.attributionSource==='BOOST').reduce((sum,order)=>sum+orderRevenue(order),0))}};
  const ranked=[...advancedProducts].sort((a,b)=>b.listingScore-a.listingScore||b.conversionRate-a.conversionRate||b.rating-a.rating);const ranking=ranked.map((item,index)=>({productId:item.id,product:item.name,currentRank:index+1,categoryRank:ranked.filter(other=>products.find(product=>String(product._id)===other.id)?.category===products.find(product=>String(product._id)===item.id)?.category).findIndex(other=>other.id===item.id)+1,health:{seo:item.listingScore>=75?'Strong':'Needs improvement',ctr:item.ctr>=5?'Strong':'Needs improvement',conversion:item.conversionRate>=8?'Strong':'Needs improvement',rating:item.rating>=4?'Strong':'Needs improvement'}}));
  const boost=advancedProducts.filter(item=>item.boosted).map(item=>{const product=products.find(row=>String(row._id)===item.id)!;const boostEvents=events.filter(event=>String(event.productId)===item.id&&event.source==='BOOST');const boostOrders=completed.filter(order=>String(order.productId)===item.id&&order.attributionSource==='BOOST');const revenue=round(boostOrders.reduce((sum,order)=>sum+orderRevenue(order),0));return {product:item.name,status:product.boostEnds&&product.boostEnds.getTime()>Date.now()?'ACTIVE':'ENDED',endsAt:product.boostEnds?.toISOString()??null,impressions:boostEvents.filter(event=>event.type==='LISTING_IMPRESSION').length,clicks:boostEvents.filter(event=>event.type==='PRODUCT_VIEW').length,orders:boostOrders.length,revenue}});
  const normalizeVariant=(value:unknown)=>String(value??'').trim().toLocaleLowerCase();
  const competitorBenchmarks=products.flatMap(product=>{const peers=marketProducts.filter(peer=>peer.category===product.category&&peer.subcategory===product.subcategory);const listingScore=advancedProducts.find(item=>item.id===String(product._id))?.listingScore??0;const buildRow=(variant:{size?:string|null;color?:string|null;price:number;discountPrice?:number|null}|null,prices:number[])=>{const price=variant?.discountPrice??variant?.price??product.discountPrice??product.price;const competitorAverage=prices.length?round(prices.reduce((sum,item)=>sum+item,0)/prices.length):null;const priceGap=competitorAverage==null?null:round(price-competitorAverage);return {product:product.name,variant:variant?[variant.color,variant.size].filter(Boolean).join(' · ')||'Variant':'Base product',price,competitorAverage,priceGap,sampleSize:prices.length,position:priceGap==null?'No comparable variant':Math.abs(priceGap)<0.01?'At market':priceGap<0?'Below market':'Above market',listingScore}};if(product.variants.length){return product.variants.map(variant=>buildRow(variant,peers.flatMap(peer=>peer.variants).filter(candidate=>normalizeVariant(candidate.size)===normalizeVariant(variant.size)&&normalizeVariant(candidate.color)===normalizeVariant(variant.color)).map(candidate=>candidate.discountPrice??candidate.price)))}return [buildRow(null,peers.filter(peer=>peer.variants.length===0).map(peer=>peer.discountPrice??peer.price))]});
  const variantEconomics=products.flatMap(product=>{const rows=product.variants.length?product.variants.map(variant=>({id:String(variant._id),label:[variant.color,variant.size].filter(Boolean).join(' · ')||'Default',sku:variant.sku??'',price:variant.discountPrice??variant.price,stock:variant.quantity,unitCost:(variant.costPrice??0)+(variant.packagingCost??0)+(variant.otherCost??0)})):[{id:'base',label:'Base product',sku:'',price:product.discountPrice??product.price,stock:product.quantity,unitCost:(product.costPrice??0)+(product.packagingCost??0)+(product.otherCost??0)}];return rows.map(variant=>{const variantOrders=completed.filter(order=>String(order.productId)===String(product._id)&&(variant.id==='base'?!order.variantId:String(order.variantId)===variant.id));const units=variantOrders.reduce((sum,order)=>sum+order.quantity,0),revenue=round(variantOrders.reduce((sum,order)=>sum+orderRevenue(order),0)),cost=round(variantOrders.reduce((sum,order)=>sum+(order.unitCost??0)*order.quantity,0)),unitCost=units?round(cost/units):variant.unitCost,profit=revenue;return {product:product.name,variant:variant.label,sku:variant.sku,price:variant.price,stock:product.status==='PRE_ORDER_AVAILABLE'?null:variant.stock,availabilityMode:product.status==='PRE_ORDER_AVAILABLE'?'PRE_ORDER':'STOCKED',orders:variantOrders.length,units,revenue,unitCost,cost,profit,margin:revenue+cost?round(profit/(revenue+cost)*100):0}})});
  const decided=orders.filter(order=>order.status!=='PENDING');const accepted=decided.filter(order=>order.status!=='CANCELLED').length;const fulfilled=orders.filter(order=>finished(order.status)).length;const ratedProducts=products.filter(product=>product.rating>0);const averageRating=ratedProducts.length?round(ratedProducts.reduce((sum,product)=>sum+product.rating,0)/ratedProducts.length):0;const acceptanceRate=decided.length?round(accepted/decided.length*100):0;const sellerPerformance={score:Math.round((acceptanceRate*.3+(orders.length?fulfilled/orders.length*35:0)+(averageRating/5)*25+(products.length?products.filter(product=>['ACTIVE','PRE_ORDER_AVAILABLE'].includes(product.status)).length/products.length*10:0))*100)/100,acceptanceRate,fulfillmentRate:orders.length?round(fulfilled/orders.length*100):0,cancellationRate:orders.length?round(cancelled.length/orders.length*100):0,averageRating,availableListings:products.filter(product=>['ACTIVE','PRE_ORDER_AVAILABLE'].includes(product.status)).length,totalListings:products.length};const funnelStages=[{name:'Impression',value:impressions},{name:'Product view',value:views},{name:'Add to cart',value:cartAdds},{name:'Checkout',value:checkoutStarts},{name:'Purchase',value:completed.length}];const drops=funnelStages.slice(1).map((stage,index)=>({from:funnelStages[index]!.name,to:stage.name,drop:funnelStages[index]!.value?round(Math.max(0,funnelStages[index]!.value-stage.value)/funnelStages[index]!.value*100):0}));const biggestDrop=[...drops].sort((a,b)=>b.drop-a.drop)[0]??null;
  res.json({success:true,message:'Premium seller intelligence loaded',data:{benchmarkSampleLimit:1000,ppcMeasurement:'ATTRIBUTED_EVENTS_ONLY_ESTIMATED_SPEND',rangeDays:days,summary:{impressions,views,cartAdds,orders:completed.length,sales,repeatCustomers:repeatCustomers.length,uniqueCustomers:customers.length,profit,margin:sales+cost?round(profit/(sales+cost)*100):0,ppcSpend:totalPpcSpend,acos:sales?round(totalPpcSpend/sales*100):0,tacos:sales?round(totalPpcSpend/sales*100):0},products:advancedProducts,variantEconomics,topProducts:advancedProducts.slice(0,3),lostPotential:losses,keywords,keywordSuggestions:keywords.filter(item=>item.searches>0).slice(0,15),searchOpportunities:keywords.filter(item=>item.orders===0||item.conversionRate<10).slice(0,10),demand:[...demandMap.values()].sort((a,b)=>b.orders-a.orders),customers:{repeatRate:customers.length?round(repeatCustomers.length/customers.length*100):0,repeat:repeatCustomers.map((customer,index)=>({...customer,buyer:`Returning customer ${index+1}`})),top:customers.slice(0,10).map((customer,index)=>({...customer,buyer:`Customer ${index+1}`})),averageNetRevenue:customers.length?round(sales/customers.length):0},inventory:advancedProducts.map(item=>({id:item.id,name:item.name,status:item.status,baseQuantity:item.stock,variantQuantity:item.stock,variantCount:products.find(product=>String(product._id)===item.id)?.variants.length??0,rating:item.rating,boosted:item.boosted,daysOfCover:item.daysOfCover,reorderQuantity:item.reorderQuantity,forecast7:item.forecast7,forecast30:item.forecast30,deadStock:item.deadStock})),ppc:campaignPerformance,funnel:{impressions,views,cartAdds,checkoutStarts,orders:completed.length,stages:funnelStages,biggestDrop,viewDrop:views?round(Math.max(0,views-cartAdds)/views*100):0,cartAbandonment:cartAdds?round(Math.max(0,cartAdds-completed.length)/cartAdds*100):0},traffic,attribution:attributed,ranking,boost,sellerPerformance,orderAnalytics:{total:orders.length,pending:orders.filter(order=>order.status==='PENDING').length,preparing:orders.filter(order=>['ACCEPTED','PREPARING','READY','PACKED','OUT_FOR_DELIVERY'].includes(order.status)).length,completed:fulfilled,cancelled:cancelled.length,acceptanceRate:sellerPerformance.acceptanceRate,fulfillmentRate:sellerPerformance.fulfillmentRate},competitor:competitorBenchmarks,listingQuality:advancedProducts.map(item=>({productId:item.id,product:item.name,score:item.listingScore,actions:item.qualityActions})),reviews:reviewSignals,cancellations:{count:cancelled.length,rate:orders.length?round(cancelled.length/orders.length*100):0,reasons:Object.entries(Object.groupBy(cancelled,item=>item.cancellationReason??'Buyer cancelled')).map(([reason,rows])=>({reason,count:rows?.length??0}))},cohorts:[...cohortMap.values()].map(item=>({cohort:item.cohort,customers:item.customers.size,orders:item.orders,revenue:round(item.revenue)})),alerts}});
}catch(error){next(error)}});

sellerAnalyticsRouter.get('/',requireRole('SELLER','ADMIN'),async(req,res,next)=>{try{
  const sellerId=scopedSellerId(req);const days=z.coerce.number().int().min(1).max(365).catch(30).parse(req.query.days);const now=new Date();const start=dhakaRangeStart(days);const previousStart=new Date(start.getTime()-days*86400000);
  const [allOrders,products,coupons]=await Promise.all([OrderModel.find({sellerId,createdAt:{$gte:previousStart}}).sort({createdAt:-1}).limit(20001).lean(),ProductModel.find({sellerId}).lean(),CouponModel.find({sellerId}).lean()]);
  if(allOrders.length>20000||products.length>2000){res.status(422).json({success:false,message:'This detailed report is too large. Choose a shorter period.'});return}
  const orders=allOrders.filter(order=>order.createdAt>=start);const previous=allOrders.filter(order=>order.createdAt>=previousStart&&order.createdAt<start);const completed=orders.filter(order=>finished(order.status));const previousCompleted=previous.filter(order=>finished(order.status));const revenue=round(completed.reduce((sum,order)=>sum+orderRevenue(order),0));const previousRevenue=round(previousCompleted.reduce((sum,order)=>sum+orderRevenue(order),0));const grossSales=round(completed.reduce((sum,order)=>sum+order.total+(order.discountAmount??0),0)),totalCost=round(completed.reduce((sum,order)=>sum+(order.unitCost??0)*order.quantity,0));const unitsSold=completed.reduce((sum,order)=>sum+order.quantity,0);const previousUnits=previousCompleted.reduce((sum,order)=>sum+order.quantity,0);const cancelled=orders.filter(order=>order.status==='CANCELLED').length;
  const dayMap=new Map<string,{revenue:number;orders:number;units:number}>();for(let offset=0;offset<days;offset++){const date=new Date(start.getTime()+offset*86400000);dayMap.set(dhakaDay(date),{revenue:0,orders:0,units:0})}for(const order of completed){const point=dayMap.get(dhakaDay(order.createdAt));if(point){point.orders+=1;point.revenue=round(point.revenue+orderRevenue(order));point.units+=order.quantity}}
  const productMap=new Map<string,{id:string;name:string;image:string;status:string;rating:number;boosted:boolean;orders:number;units:number;revenue:number;discounts:number}>();for(const product of products)productMap.set(String(product._id),{id:String(product._id),name:product.name,image:product.images[0]??'',status:product.status,rating:product.rating,boosted:product.boosted,orders:0,units:0,revenue:0,discounts:0});
  const variantMap=new Map<string,{product:string;variant:string;orders:number;units:number;revenue:number;cost:number;profit:number;margin:number}>();const buyerMap=new Map<string,{buyer:string;orders:number;spend:number;units:number}>();for(const order of completed){const product=productMap.get(String(order.productId));if(product){product.orders+=1;product.units+=order.quantity;product.revenue=round(product.revenue+orderRevenue(order));product.discounts=round(product.discounts+(order.discountAmount??0))}const key=`${order.productId}:${order.variantId??'base'}`;const item=variantMap.get(key)??{product:order.food,variant:order.variantLabel??'Base product',orders:0,units:0,revenue:0,cost:0,profit:0,margin:0};item.orders+=1;item.units+=order.quantity;item.revenue=round(item.revenue+orderRevenue(order));item.cost=round(item.cost+(order.unitCost??0)*order.quantity);item.profit=item.revenue;item.margin=item.revenue+item.cost?round(item.profit/(item.revenue+item.cost)*100):0;variantMap.set(key,item);const buyerKey=String(order.buyerId);const buyer=buyerMap.get(buyerKey)??{buyer:order.buyer,orders:0,spend:0,units:0};buyer.orders+=1;buyer.spend=round(buyer.spend+order.total);buyer.units+=order.quantity;buyerMap.set(buyerKey,buyer)}
  const statusCounts=Object.fromEntries(['PENDING','ACCEPTED','PREPARING','READY','OUT_FOR_DELIVERY','PACKED','DELIVERED','COMPLETED','CANCELLED','RETURNED'].map(status=>[status,orders.filter(order=>order.status===status).length]));const repeatBuyers=[...buyerMap.values()].filter(buyer=>buyer.orders>1).length;const totalDiscounts=round(completed.reduce((sum,order)=>sum+(order.discountAmount??0),0));
  const couponPerformance=coupons.map(coupon=>{const couponOrders=completed.filter(order=>String(order.couponId)===String(coupon._id));return {id:String(coupon._id),code:coupon.code,active:coupon.active,discountPercent:coupon.discountPercent,redemptions:coupon.redemptions,periodOrders:couponOrders.length,revenue:round(couponOrders.reduce((sum,order)=>sum+orderRevenue(order),0)),discountGiven:round(couponOrders.reduce((sum,order)=>sum+(order.discountAmount??0),0))}}).sort((a,b)=>b.periodOrders-a.periodOrders);
  const inventory=products.map(product=>({id:String(product._id),name:product.name,image:product.images[0]??'',status:product.status,quantity:product.quantity,variantCount:product.variants.length,variantQuantity:product.variants.reduce((sum,variant)=>sum+variant.quantity,0),rating:product.rating,orders:product.orders,boosted:product.boosted}));
  const summary={revenue,totalCost,grossSales,netSales:revenue,totalOrders:orders.length,completedOrders:completed.length,unitsSold,averageOrderValue:completed.length?round(revenue/completed.length):0,cancelledOrders:cancelled,cancellationRate:orders.length?round(cancelled/orders.length*100):0,totalListings:products.length,activeListings:products.filter(product=>['ACTIVE','PRE_ORDER_AVAILABLE'].includes(product.status)).length,boostedListings:products.filter(product=>product.boosted&&(!product.boostEnds||product.boostEnds.getTime()>now.getTime())).length,totalDiscounts,uniqueBuyers:buyerMap.size,repeatBuyerRate:buyerMap.size?round(repeatBuyers/buyerMap.size*100):0};
  res.json({success:true,message:'Detailed seller analytics loaded',data:{rangeDays:days,summary,comparison:{revenue:delta(revenue,previousRevenue),orders:delta(completed.length,previousCompleted.length),units:delta(unitsSold,previousUnits),averageOrderValue:delta(summary.averageOrderValue,previousCompleted.length?round(previousRevenue/previousCompleted.length):0)},trend:[...dayMap].map(([date,value])=>({date,label:new Date(`${date}T00:00:00Z`).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'Asia/Dhaka'}),...value})),statusCounts,topProducts:[...productMap.values()].sort((a,b)=>b.revenue-a.revenue||b.orders-a.orders).slice(0,20),variantPerformance:[...variantMap.values()].sort((a,b)=>b.revenue-a.revenue),couponPerformance,topBuyers:[...buyerMap.values()].sort((a,b)=>b.spend-a.spend).slice(0,10).map((buyer,index)=>({...buyer,buyer:`Customer ${index+1}`})),inventory,recentOrders:orders.slice(0,10).map(order=>({id:String(order._id),food:order.food,image:order.image,buyer:'Customer',quantity:order.quantity,total:order.total,status:order.status,couponCode:order.couponCode,createdAt:order.createdAt.toISOString()}))}});
}catch(error){next(error)}});
