import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Button,Empty,Loading,Modal } from '../components/ui';
import { marketplaceAdminService } from '../services/account';
export function MarketplaceOverview(){const query=useQuery({queryKey:['marketplace-overview'],queryFn:marketplaceAdminService.overview});if(query.isLoading)return <Loading/>;if(!query.data)return <Empty title="Unable to load overview" body={query.error?.message}/>;const data=query.data;return <><h1 className="mb-6 text-3xl font-extrabold">Marketplace overview</h1><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['Users',data.users,'/admin/users'],['Active sellers',data.sellers,'/admin/users'],['Pending applications',data.approvals,'/admin/approvals'],['Open reports',data.reports,'/admin/reports'],['Completed orders',data.completedOrders,'/admin/foods'],['Marketplace sales (BDT)',data.sales,'/admin/analytics']].map(([label,value,to])=><Link to={String(to)} key={label} className="card p-6"><p className="text-stone-500">{label}</p><b className="mt-3 block text-3xl">{Number(value).toLocaleString()}</b></Link>)}</div><p className="mt-5 text-sm text-stone-500">Marketplace sales are completed product orders. Company earnings from boosts and premium analytics are shown in Analytics.</p></>}
export function MarketplaceInventory(){
 const [page,setPage]=useState(1),[status,setStatus]=useState('ALL'),[q,setQ]=useState(''),[target,setTarget]=useState<string|null>(null),[reason,setReason]=useState('');const qc=useQueryClient();
 const query=useQuery({queryKey:['admin-inventory',page,status,q],queryFn:()=>marketplaceAdminService.products(page,status,q)});
 const remove=useMutation({mutationFn:()=>marketplaceAdminService.remove(target!,reason),meta:{successMessage:'Listing removed.'},onSuccess:()=>{setTarget(null);setReason('');void qc.invalidateQueries({queryKey:['admin-inventory']});void qc.invalidateQueries({queryKey:['foods']});void qc.invalidateQueries({queryKey:['product']});}});
 return <><h1 className="mb-6 text-3xl font-extrabold">Product inventory</h1><div className="mb-5 flex gap-3"><input aria-label="Search products or sellers" className="field" placeholder="Search products or sellers" value={q} onChange={event=>{setQ(event.target.value);setPage(1)}}/><select aria-label="Product status" className="field" value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}>{['ALL','ACTIVE','PAUSED','PRE_ORDER_AVAILABLE','OUT_OF_STOCK','REMOVED'].map(value=><option key={value}>{value}</option>)}</select></div>{query.isLoading?<Loading/>:query.isError?<Empty title="Unable to load inventory" body={query.error.message}/>:<><div className="card overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Product','Seller','Status','Action'].map(label=><th className="p-4" key={label}>{label}</th>)}</tr></thead><tbody>{query.data?.items.map(item=><tr key={item.id} className="border-t"><td className="p-4">{item.name}</td><td className="p-4">{item.seller}</td><td className="p-4">{item.status}{item.removalReason&&<p className="text-xs text-stone-500">{item.removalReason}</p>}</td><td className="p-4">{item.status!=='REMOVED'&&<Button variant="danger" onClick={()=>setTarget(item.id)}>Remove</Button>}</td></tr>)}</tbody></table></div><div className="mt-5 flex items-center gap-4"><Button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>{page} / {query.data?.totalPages??1}</span><Button disabled={page>=(query.data?.totalPages??1)} onClick={()=>setPage(page+1)}>Next</Button></div></>}<Modal open={!!target} title="Remove listing" onClose={()=>setTarget(null)}><label><span className="label">Moderation reason</span><textarea className="field" value={reason} maxLength={1000} onChange={event=>setReason(event.target.value)}/></label><Button className="mt-4" variant="danger" disabled={reason.trim().length<3||remove.isPending} onClick={()=>remove.mutate()}>Confirm removal</Button></Modal></>;
}
