import { zodResolver } from '@hookform/resolvers/zod';
import { useQuery } from '@tanstack/react-query';
import { CalendarDays } from 'lucide-react';
import { useEffect,useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link,useLocation,useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { Button,Spinner } from '../components/ui';
import { authService,sellerApplicationService } from '../services';
import { useAuth } from '../store/auth';
import { toast } from '../store/toast';

const loginSchema=z.object({email:z.string().email('Enter a valid email'),password:z.string().min(8,'Password must be at least 8 characters')});
const registerSchema=loginSchema.extend({name:z.string().trim().min(2,'Enter your full name')});

export function RealLogin(){
  const location=useLocation();
  const [mode,setMode]=useState<'login'|'register'>('login');
  const [serverError,setServerError]=useState('');
  const setUser=useAuth(state=>state.setUser);const nav=useNavigate();
  const form=useForm<z.infer<typeof registerSchema>>({resolver:zodResolver(registerSchema),defaultValues:{name:'Buyer',email:'',password:''}});
  const submit=form.handleSubmit(async values=>{if(mode==='register'&&(values.password.length<10||!/[a-z]/.test(values.password)||!/[A-Z]/.test(values.password)||!/\d/.test(values.password))){form.setError('password',{message:'Use 10+ characters with uppercase, lowercase, and a number'});return}try{setServerError('');const user=mode==='register'?await authService.register(values):await authService.login({email:values.email,password:values.password});setUser(user);toast.success(mode==='register'?'Account created successfully.':'Signed in successfully.');const requested=(location.state as {from?:{pathname?:string}}|null)?.from?.pathname;nav(requested??`/${user.role.toLowerCase()}/dashboard`,{replace:true})}catch(error){setServerError((error as Error).message);toast.error(error)}});
  return <div className="container-x py-20"><div className="card mx-auto max-w-lg p-8"><div className="mb-6 grid grid-cols-2 rounded-xl bg-stone-100 p-1"><button className={`rounded-lg py-2 text-sm font-bold ${mode==='login'?'bg-white shadow':''}`} onClick={()=>{setMode('login');setServerError('');form.clearErrors()}}>Sign in</button><button className={`rounded-lg py-2 text-sm font-bold ${mode==='register'?'bg-white shadow':''}`} onClick={()=>{setMode('register');setServerError('');form.clearErrors()}}>Create account</button></div><h1 className="text-3xl font-extrabold">{mode==='login'?'Welcome back':'Create your buyer account'}</h1><p className="mt-2 text-stone-500">{mode==='login'?'Sign in securely to continue.':'All new accounts start as buyers. You can apply to become a seller later.'}</p><form onSubmit={submit} className="mt-6 space-y-4">{mode==='register'&&<label className="block"><span className="label">Full name</span><input autoComplete="name" className="field" {...form.register('name')}/><small className="text-red-600">{form.formState.errors.name?.message}</small></label>}<label className="block"><span className="label">Email</span><input type="email" autoComplete="email" className="field" {...form.register('email')}/><small className="text-red-600">{form.formState.errors.email?.message}</small></label><label className="block"><span className="label">Password</span><input type="password" autoComplete={mode==='register'?'new-password':'current-password'} className="field" {...form.register('password')}/><small className="text-red-600">{form.formState.errors.password?.message}</small></label>{serverError&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{serverError}</p>}<Button className="w-full" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?<Spinner/>:mode==='login'?'Sign in':'Create buyer account'}</Button></form></div></div>
}

const sellerSchema=z.object({store:z.string().trim().min(3),phone:z.string().trim().min(10),bracuId:z.string().trim().min(6),description:z.string().trim().min(30,'Tell us a little more (30 characters minimum)')});
export function RealBecomeSeller(){
  const user=useAuth(state=>state.user);const restore=useAuth(state=>state.restore);const nav=useNavigate();const [done,setDone]=useState(false),[serverError,setServerError]=useState('');const form=useForm<z.infer<typeof sellerSchema>>({resolver:zodResolver(sellerSchema)});const {data:application,isLoading}=useQuery({queryKey:['my-seller-application',user?.id],queryFn:sellerApplicationService.mine,enabled:!!user,refetchInterval:60_000});
  useEffect(()=>{if(application?.status!=='APPROVED')return;void restore().then(()=>nav('/seller/dashboard',{replace:true}))},[application?.status,nav,restore]);
  if(!user)return <div className="container-x py-20"><div className="card mx-auto max-w-xl p-10 text-center"><h1 className="text-3xl font-extrabold">Sign in as a buyer first</h1><p className="mt-3 text-stone-500">Every seller starts with a buyer account.</p><Link className="btn-primary mt-6" to="/login">Sign in or create account</Link></div></div>;
  if(isLoading)return <div className="container-x grid min-h-96 place-items-center"><Spinner/></div>;
  if(done||application?.status==='PENDING')return <div className="container-x py-20"><div className="card mx-auto max-w-xl p-10 text-center"><CalendarDays className="mx-auto text-brand-600" size={52}/><h1 className="mt-4 text-3xl font-extrabold">Your request is pending</h1><p className="mt-3 text-stone-500">Your seller upgrade request for <b>{application?.store??'your store'}</b> is waiting for admin review. Your buyer access stays active meanwhile.</p><Link className="btn-primary mt-6" to="/buyer/dashboard">Back to dashboard</Link></div></div>;
  return <div className="container-x py-14"><div className="mx-auto max-w-2xl"><p className="font-bold text-brand-600">SELL ON CAMPUS</p><h1 className="mt-2 text-4xl font-extrabold">Upgrade your buyer account.</h1><p className="mt-3 text-stone-500">Applying as <b>{user.name}</b> ({user.email}). Approval changes this account’s role to seller.</p><form onSubmit={form.handleSubmit(async value=>{try{setServerError('');await sellerApplicationService.submit(value);toast.success('Seller application submitted.');setDone(true)}catch(error){setServerError((error as Error).message);toast.error(error)}})} className="card mt-8 grid gap-5 p-7 sm:grid-cols-2"><label><span className="label">Store name</span><input className="field" {...form.register('store')}/><small className="text-red-600">{form.formState.errors.store?.message}</small></label><label><span className="label">Phone number</span><input className="field" {...form.register('phone')}/><small className="text-red-600">{form.formState.errors.phone?.message}</small></label><label className="sm:col-span-2"><span className="label">BRACU ID / affiliation</span><input className="field" {...form.register('bracuId')}/><small className="text-red-600">{form.formState.errors.bracuId?.message}</small></label><label className="sm:col-span-2"><span className="label">Store and product description</span><textarea className="field min-h-28" {...form.register('description')}/><small className="text-red-600">{form.formState.errors.description?.message}</small></label>{serverError&&<p className="sm:col-span-2 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{serverError}</p>}<Button className="sm:col-span-2" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?<Spinner/>:'Submit application'}</Button></form></div></div>
}
