import {useState} from 'react';import {useMutation,useQueryClient} from '@tanstack/react-query';import {Navigate,Outlet,Route,Routes,useLocation} from 'react-router-dom';import {PublicLayout} from './components/Layout';import {useAuth} from './store/auth';import type {Role} from './types';import {reactivationService} from './services';import {BecomeSeller,Cart,FoodDetails,Foods,Home,Login} from './pages/PublicPages';import {AdminDashboard,AdminFoods,AdminSellers,AdminUsers,Analytics,Approvals,BuyerDashboard,BuyerOrders,DashboardLayout,FoodForm,GenericPage,Reports,Saved,SellerBusinessAnalytics,SellerCoupons,SellerDashboard,SellerFoods,SellerOrders,SellerSettings,SeoManager} from './pages/DashboardPages';
function Protected({role}:{role:Role}){const {user}=useAuth(),loc=useLocation();if(!user)return <Navigate to="/login" state={{from:loc}} replace/>;if(user.role!==role)return <Navigate to={`/${user.role.toLowerCase()}/dashboard`} replace/>;if(['BANNED','REJECTED','PENDING'].includes(user.status))return <StatusBlock/>;if(user.status==='SUSPENDED'||(user.role==='SELLER'&&user.status==='FROZEN'))return <RestrictedAccount/>;return <DashboardLayout><Outlet/></DashboardLayout>}
function RestrictedAccount(){const {user,setUser}=useAuth();const qc=useQueryClient();const [reason,setReason]=useState('');const request=useMutation({mutationFn:()=>reactivationService.request(user!,reason),onSuccess:()=>qc.invalidateQueries({queryKey:['reactivation-requests']})});if(!user)return null;return <div className="grid min-h-screen place-items-center bg-stone-50 p-4"><div className="card w-full max-w-xl p-8 text-center"><div className="text-5xl">{user.status==='FROZEN'?'FROZEN':'SUSPENDED'}</div><h1 className="mt-5 text-3xl font-extrabold">Account {user.status.toLowerCase()}</h1><p className="mt-3 text-stone-500">{user.role==='SELLER'?'You cannot create listings, manage orders, or perform delivery actions until an admin approves reactivation.':'You cannot place orders or use buyer actions while this suspension is active.'}</p>{user.role==='SELLER'&&!request.isSuccess&&<><textarea className="field mt-6 min-h-24 text-left" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Tell the admin why your account should be reactivated..."/><button className="btn-primary mt-3 w-full" disabled={!reason.trim()||request.isPending} onClick={()=>request.mutate()}>{request.isPending?'Sending...':'Request reactivation'}</button></>}{request.isSuccess&&<div className="mt-6 rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-700">Request sent. Waiting for admin approval.</div>}<button className="btn-secondary mt-3 w-full" onClick={()=>setUser(null)}>Log out</button></div></div>}
function StatusBlock(){const {user,setUser}=useAuth();return <div className="grid min-h-screen place-items-center bg-stone-50 p-4"><div className="card max-w-lg p-10 text-center"><div className="text-5xl">{user?.status==='BANNED'?'BLOCKED':'PENDING'}</div><h1 className="mt-5 text-3xl font-extrabold">{user?.status==='PENDING'?'Waiting for admin approval.':user?.status==='REJECTED'?'Application rejected':'Account access restricted'}</h1><p className="mt-3 text-stone-500">{user?.reason??'Your account status currently prevents access to marketplace actions. Contact support if you believe this is a mistake.'}</p><button className="btn-primary mt-6" onClick={()=>setUser(null)}>Return to demo login</button></div></div>}
const Public=({children}:{children:React.ReactNode})=><PublicLayout>{children}</PublicLayout>;
function MarketplaceRoute(){const location=useLocation();return <Foods key={location.search}/>};
function SellerApplicationRoute(){const {user}=useAuth();return user?.role==='SELLER'?<Navigate to="/seller/dashboard" replace/>:<BecomeSeller/>}
export default function App(){return <Routes><Route path="/" element={<Public><Home/></Public>}/><Route path="/cart" element={<Public><Cart/></Public>}/><Route path="/categories" element={<Navigate to="/foods" replace/>}/><Route path="/foods" element={<Public><MarketplaceRoute/></Public>}/><Route path="/foods/:id" element={<Public><FoodDetails/></Public>}/><Route path="/become-seller" element={<Public><SellerApplicationRoute/></Public>}/><Route path="/login" element={<Public><Login/></Public>}/><Route path="/register" element={<Navigate to="/login"/>}/><Route element={<Protected role="BUYER"/>}><Route path="/buyer/dashboard" element={<BuyerDashboard/>}/><Route path="/buyer/orders" element={<BuyerOrders/>}/><Route path="/buyer/saved" element={<Saved/>}/><Route path="/buyer/settings" element={<GenericPage title="Account settings"/>}/></Route><Route element={<Protected role="SELLER"/>}><Route path="/seller/dashboard" element={<SellerDashboard/>}/><Route path="/seller/foods" element={<SellerFoods/>}/><Route path="/seller/foods/new" element={<FoodForm/>}/><Route path="/seller/foods/:id/edit" element={<FoodForm/>}/><Route path="/seller/orders" element={<SellerOrders/>}/><Route path="/seller/coupons" element={<SellerCoupons/>}/><Route path="/seller/seo" element={<SeoManager/>}/><Route path="/seller/analytics" element={<Analytics/>}/><Route path="/seller/settings" element={<SellerSettings/>}/></Route><Route element={<Protected role="ADMIN"/>}><Route path="/admin/dashboard" element={<AdminDashboard/>}/><Route path="/admin/users" element={<AdminUsers/>}/><Route path="/admin/approvals" element={<Approvals/>}/><Route path="/admin/reports" element={<Reports/>}/><Route path="/admin/foods" element={<AdminFoods/>}/><Route path="/admin/sellers" element={<AdminSellers/>}/><Route path="/admin/sellers/:id" element={<SellerBusinessAnalytics/>}/><Route path="/admin/analytics" element={<Analytics admin/>}/><Route path="/admin/settings" element={<GenericPage title="Platform settings"/>}/></Route><Route path="*" element={<Navigate to="/"/>}/></Routes>}









